name: Build and release Mutant Remix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-mutant-remix:
    runs-on: ubuntu-latest

    steps:
      # Checkout build files
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # Install build dependencies
      - name: Install node
        uses: actions/setup-node@v3

      - name: Install python
        uses: actions/setup-python@v3
        with:
          cache: 'pip'

      - name: Install python dependencies
        run: |
          pip install -r orxporter/requirements.txt
          pip install -r forc/requirements.txt

      - name: Install apt dependencies
        uses: Eeems-Org/apt-cache-action@v1
        with:
          packages: libimage-exiftool-perl webp libpng-dev

      - name: Install oxipng
        uses: baptiste0928/cargo-install@v2
        with:
          crate: oxipng

      - name: Install svgcleaner
        uses: baptiste0928/cargo-install@v2
        with:
          crate: svgcleaner

      - name: Install resvg
        uses: baptiste0928/cargo-install@v2
        with:
          crate: resvg

      # Build pack
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: cache
          key: mutantremix

      - name: Run build script
        run: |
          echo "version=${{ github.run_number }}" > config.sh
          echo "threads=2" >> config.sh
          ./out_final_full.sh

      # Upload build artifacts
      - name: Upload pack artifact
        uses: actions/upload-artifact@v3
        with:
          name: final-pkg
          path: |
            out/final-pkg/mtnt_*.tar.gz
            out/final-pkg/mtnt_*.json

      - name: Upload unicode coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: unicode-coverage
          path: out/unicode-coverage/coverage.*

  publish-coverage:
    needs: build-mutant-remix
    runs-on: ubuntu-latest

    # Only run this job on push, not on PR or manual trigger
    if: github.event_name == 'push'

    steps:
      - name: Clone unicode-coverage repository
        uses: actions/checkout@v2
        with:
          repository: mutant-remix/unicode-coverage
          path: unicode-coverage
          token: ${{ secrets.COVERAGE_REPORT_PAT }}
          fetch-depth: '0'

      - name: Configure git
        run: |
          cd unicode-coverage
          git config user.name "Mutant Remix CI"
          git config user.email "noreply@example.com"

      - name: Clear unicode-coverage repository
        run: |
          cd unicode-coverage
          git reset --hard 303f8912610638be6abc81bc64612af0c815698a

      - name: Download coverage artifact
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: unicode-coverage
          path: unicode-coverage

      - name: Commit and push unicode coverage
        run: |
          cd unicode-coverage
          git add .
          git commit -m "[CI] Upload latest coverage (${{ github.run_number }})"
          git push -f origin master

  publish-draft-release:
    needs: build-mutant-remix
    runs-on: ubuntu-latest

    # Only run this job on manual trigger
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Download pack artifact
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: final-pkg
          path: final-pkg

      - name: Generate release notes
        id: release-notes
        run: |
          wget https://raw.githubusercontent.com/mutant-remix/mutant-remix/master/.github/release_notes/base.md
          sed -i "s/{{ version }}/${{ github.run_number }}/g" base.md

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "release_notes<<$EOF" >> "$GITHUB_OUTPUT"
          cat base.md >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            final-pkg/mtnt_*.tar.gz
            final-pkg/mtnt_*.json
          tag_name: v${{ github.run_number }}
          name: Mutant Remix v${{ github.run_number }}
          draft: true
          body: ${{ steps.release-notes.outputs.release_notes }}
