name: Build and release Mutant Remix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-mutant-remix:
    runs-on: ubuntu-latest

    steps:
      # Checkout build files
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # Install build dependencies
      - name: Install node
        uses: actions/setup-node@v3

      - name: Install python
        uses: actions/setup-python@v3
        with:
          cache: 'pip'

      - name: Install apt dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: resvg libimage-exiftool-perl webp libpng-dev libaom-dev
          version: 1.0

      - name: Install python dependencies
        run: pip install -r orxporter/requirements.txt

      - name: Install oxipng
        uses: baptiste0928/cargo-install@v2
        with:
          crate: oxipng

      - name: Install svgcleaner
        uses: baptiste0928/cargo-install@v2
        with:
          crate: svgcleaner

      # Build pack
      - name: Run build script
        run: ./out_final_full.sh

      # Upload build artifacts
      - name: Upload pack artifact
        uses: actions/upload-artifact@v3
        with:
          name: final-pkg
          path: |
            out/final-pkg/mtnt_*.tar.gz
            out/final-pkg/mtnt_*.json

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: out/coverage/coverage.*